security:
    providers:
        inDatabase:
            entity:
                class:  App\Entity\User
                property: email

    encoders:
        App\Entity\User: plaintext

    role_hierarchy:
        ROLE_ADMIN: ROLE_USER
        ROLE_DEV: [ROLE_USER, ROLE_ADMIN]

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: true
            provider: inDatabase
            form_login:
                check_path: security_login
                login_path: security_login
                default_target_path: /backoffice
                username_parameter: email
                password_parameter: password
                csrf_parameter: _csrf_security_token
            logout:
                path: security_logout

    access_control:
        - { path: ^/backoffice, roles: ROLE_ADMIN }
    # - { path: ^/profile, roles: ROLE_USER }
