security:
    # https://symfony.com/doc/current/security.html#where-do-users-come-from-user-providers
    providers:
        database_provider:
            entity:
                class: App\Entity\Users
                    # the property to query by - e.g. username, email, etc
                    property: email

    session_fixation_strategy: migrate

    encoders:
        App\Entity\Users:
            algorithm: bcrypt

    role_hierarchy:
        ROLE_CLIENT:      ROLE_USER
        ROLE_ADMIN:       ROLE_USER
        ROLE_DEV: [ROLE_USER, ROLE_ADMIN]

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: lazy
            provider: database_provider
            guard:
                authenticators:
                    - App\Security\LoginFormAuthentificatorAuthenticator
            logout:
                path: app_logout
    access_control:
          #- { path: ^/backoffice, roles: ROLE_ADMIN }
          #- { path: ^/profile, roles: ROLE_USER }
          #- { path: ^/login$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
